apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: "gifhub-backend-deployment"
  labels:
    app: "GifHub"
    tier: "backend"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "gifhub-backend"
  template:
    metadata:
      labels:
        app: "gifhub-backend"
    spec:
      containers:
      - name: "gifhub-backend"
        image: abdulah/gifhub-backend:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP