apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: "gifhub-backend-deployment"
  labels:
    app: "GifHub"
    tier: "backend"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "gifhub-backend"
  template:
    metadata:
      labels:
        app: "gifhub-backend"
    spec:
      containers:
      - name: "gifhub-backend"
        image: "abdulah/gifhub-backend"
        imagePullPolicy: Always
        env:
        - name: DYNAMODB_ACCESS_KEY_ID
          value: DYNAMODB_ACCESS_KEY_ID_PLACEHOLDER
        - name: DYNAMODB_SECRET_ACCESS_KEY
          value: DYNAMODB_SECRET_ACCESS_KEY_PLACEHOLDER
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP