apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: "gifhub_frontend-deployment"
  labels:
    app: "GifHub"
    tier: "frontend"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "gifhub_frontend"
  template:
    metadata:
      labels:
        app: "gifhub_frontend"
    spec:
      containers:
      - name: "gifhub_frontend"
        image: "abdulah/gifhub_frontend"
        imagePullPolicy: Always
        env:
        - name: REACT_APP_API_URL
          value: PLACE_HOLDER_API_URL
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
